### ISSUE TITLE
Feature / Add Steps of GitHub Issues and PR Tracking  Workflow

### ISSUE THREAD

**Issue by lyuich** [lyuich/brain#8]
### Write a summary of this issue
- Add Steps of GitHub Issues Workflow to `github.md`

### List the details of what to do as a list
- [x] consider step of tracking GitHub Issues and Pull Request
- [ ] add `status: test` to Labels
- [ ] add the step to `github.md`

### Any references (Describe URL of documents or webpages)
- https://github.com/lyuich/brain/blob/master/management/github.md

**Comment by lyuich** [comment]
# GitHub Issues and PR Tracking Workflow 
## Step
### Issue
- Create Issue with `status: new`
- Consider tasks before making PR with `status: in preparation`
- Finish considarations with `status: fixed`
- Review plans with `status: in review`
  - If there is problem
    - Add comments `status: reviewed`
  - else
    - set `status: fixed`
- Work on implementation with 'status: in progress`

### Pull Request
- Make a branch and pull request with `status: new`
- Continue implementing with `status: in progress`
- Finish modifications with `status: fixed`
- Review code with `status: in review`
  - If there is problem
    - Add comments `status: reviewed`
  - else
    - set `status: fixed`
- Merge and close PR with `status: done`

### Issue
- check modifications with 'status: test`
  - If there is problem
    - Create a new issue with `status: new, type: bug`
    - Link to a new issue with `status: in progress`
  - else
    - Close this issue with `status: done`

**Comment by lyuich** [comment]
Update h3
```
- Issue -> Create a new Issue and consider tasks
- Pull Request -> Review, and merge Pull Request
- Issue-> Test and close the Issue
```

**Comment by lyuich** [comment]
updated
